version: 1
disable_existing_loggers: false
formatters:
  default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s %(message)s"
    use_colors: null
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: "%(levelprefix)s %(client_addr)s - '%(request_line)s' %(status_code)s"
  loggers:
    uvicorn:
      level: "INFO"